---
# tasks file for win_ad_install
- name: install AD-Domain-Services
  win_feature:
   name: AD-Domain-Services
   state: present
  notify:
    - reboot windows servers

- name: setup AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  notify:
    - reboot windows servers

- name: reboot windows servers
  meta: flush_handlers

- name: display domain list
  win_command: "nltest /dclist:{{ ad_domain_name }}"
  register: domains

- debug:
    var: domains
...
